# -*- coding: utf-8 -*-
"""dna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nsrNzVbWDs4xmxBjEYC1fBFKKIguz-w3
"""

def dna(seq):
  #A C G T
  codon_count = []
  
  codon= seq[1].upper()
  A = codon.count("A")
  C = codon.count("C")
  G = codon.count("G")
  T = codon.count("T")
  J = codon.count("-")
  
  codon_count.append(A)
  codon_count.append(C)
  codon_count.append(G)
  codon_count.append(T)
  

  aMass = A * 135.128
  cMass = C * 111.103
  gMass = G * 151.128
  tMass = T * 125.107
  jMass = J * 100
  totalMass = aMass + cMass + gMass + tMass + jMass

  mass_list = [round((aMass/totalMass)*100, 1), round((cMass/totalMass)*100, 1), round((gMass/totalMass)*100, 1), round((tMass/totalMass)*100, 1)]

  codons_list = []
  count = 1
  build = ""
  for i in codon:
    build += i
    if count % 3 == 0:
      count = 0
      codons_list.append(build)
      build = ""
    count += 1
  Yes = mass_list[1]+mass_list[2] >= 30 and len(codons_list) >= 5 and codons_list[0] == "ATG" and codons_list[len(codons_list)-1] == "TAA" or codons_list[len(codons_list)-1] == "TGA" or codons_list[len(codons_list)-1] == "TAG"

  print("Region name:", seq[0])
  print("Nucleotides:", codon)
  print("Nuc. Counts:", codon_count)
  print("Total Mass%:", mass_list, "of", round(totalMass,1))
  print("Codons List:", codons_list)
  if Yes:
    print("Is Protein?: YES")
  else:
    print("Is Protein?: NO")

seq1 = ('cure for cancer protein', 'ATGCCACTATGGTAG')
dna(seq1)
print()
seq2 = ('captain picard hair growth protein', 'ATgCCAACATGgATGCCcGATAtGGATTgA')
dna(seq2)

