# -*- coding: utf-8 -*-
"""Hammurabi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1faRCP_pPg4G6yzY2sy7e2cPEXqwHFa5n
"""

import random
def print_intro():
  print("""Congrats, you are the newest ruler of ancient Samaria, elected for a ten year term
of office. Your duties are to distribute food, direct farming, and buy and sell land
as needed to support your people. Watch out for rat infestations and the resultant
plague! Grain is the general currency, measured in bushels. The following will help
you in your decisions:
(a) Each person needs at least 20 bushels of grain per year to survive.
(b) Each person can farm at most 10 acres of land.
(c) It takes 2 bushels of grain to farm an acre of land.
(d) The market price for land fluctuates yearly.
Rule wisely and you will be showered with appreciation at the end of your term. Rule
poorly and you will be kicked out of office!""")
  
def ask_to_buy_land(bushels, cost):
  '''Ask user how many bushels to spend buying land.'''
  acres = int(input("How many acres will you buy? "))
  while acres * cost > bushels:
    print("O great Hammurabi, we have but", bushels, "bushels of grain!")
    acres = int(input("How many acres will you buy? "))
  return acres

def ask_to_sell_land(acres):
  '''Ask user how many acres they would like to sell.'''
  soldAcres = int(input("How many acres would you like to sell? "))
  while soldAcres > acres:
    print("O great Hammurabi, we have but", acres, "acres of land!")
    soldAcres = int(input("How many acres will you sell? "))
  return soldAcres

def ask_to_feed(bushels):
  '''Ask user how many bushels they would like to use for feeding.'''
  fedBushels = int(input("How many bushels would you like to use for feeding? "))
  while fedBushels > bushels:
    print("O great Hammurabi, we have but", bushels, "bushels of grain!")
    fedBushels = int(input("How many bushels would you like to use for feeding? "))
  return fedBushels

def ask_to_cultivate(acres, population, bushels):
  '''Ask user how much land they want to plant seed in.'''
  plantedLand = int(input("How much land do you want to plant seeds in? "))
  while plantedLand > bushels or population*10 < plantedLand or plantedLand > acres:
    print("O great Hammurabi, we have but", acres, "acres of land and", population, "people in our kingdom.")
    plantedLand = int(input("How much land do you want to plant seeds in? "))
  return plantedLand

def is_plague():
  a = random.randint(1, 100)
  if(a <= 15):
    return True
  return False

def num_starving(population, bushels):
  foodNeeded = population * 20
  if bushels > foodNeeded:
    return 0
  else: 
    foodMissing = foodNeeded - bushels
    return foodMissing / 20

def num_immigrants(land, grain_in_storage, population, num_starving):
  if num_starving > 0:
    return 0
  return (20 * land + grain_in_storage) / ((100 * population) + 1)

def get_harvest():
  
  return random.randint(1, 8)

def do_rats_infest():
  ''' return true on a 40% chance '''
  return random.randint(1, 100) <= 40

def percent_destroyed():
  ''' return 10 - 30 % '''
  return random.randint(1, 3) / 10

def price_of_land():
  ''' determines the price of land '''
  return random.randint(16, 22)



def Hammurabi():
  starved = 0
  immigrants = 5
  population = 100
  harvest = 3000 # total bushels harvested
  bushels_per_acre = 3 # amount harvested for each acre planted
  rats_ate = 200 # bushels destroyed by rats
  bushels_in_storage = 2800
  acres_owned = 1000
  cost_per_acre = 19 # each acre costs this many bushels
  plague_deaths = 0
  #stuff that will be used for stat display at the end
  totalStarved = 0
  didStarveEnd = False
  totalDeaths = 0
  totalRatDam = 0
  totalBushelsMade = 0
  print_intro()
  for i in range(1, 11):
    print("")
    print("O great Hammurabi!")
    print("You are in year " + str(i) + " of your ten year rule.")
    print("In the previous year " + str(starved) + " people starved to death.")
    print("In the previous year " + str(immigrants) + " people entered the kingdom.")
    print("The population is now " + str(population) + ".")
    print("We harvested " + str(harvest) + " bushels at " + str(bushels_per_acre) + " bushels per acre.")
    print("Rats destroyed " + str(rats_ate) + " bushels, leaving " + str(bushels_in_storage) + " in storage.")
    print("The city owns " + str(acres_owned) + " acres of land.")
    print("Land is currently worth " + str(cost_per_acre) + " bushels per acre")
    print("There were " + str(plague_deaths) + " from the plague.")

    #reset the variables
    rats_ate = 0
    plague_deaths = 0
    starved = 0
    harvest = 0
    

    #buying land
    acresBought = ask_to_buy_land(bushels_in_storage, cost_per_acre)
    acres_owned += acresBought #adding actes bought to land
    bushels_in_storage -= acresBought*cost_per_acre #subtract bushels cost
    print("You now have", bushels_in_storage, "bushels remaining. \n") #display remaining bushels

    #check for selling land
    if(acresBought == 0):
      soldLand = ask_to_sell_land(acres_owned) #land sold
      bushels_in_storage += soldLand * cost_per_acre #bushels added for land sold
      totalBushelsMade += soldLand * cost_per_acre #add to endgame stat count
      acres_owned -= soldLand #take away the land you sold
      print("You now have", bushels_in_storage, "bushels remaining. \n") #remaining bushels

    #asking for the number of bushels for food
    bushels_for_food = ask_to_feed(bushels_in_storage)
    bushels_in_storage -= bushels_for_food #take away the bushels from storage
    print("You now have", bushels_in_storage, "bushels remaining. \n") #bushels remaining

    cultivatedLand = ask_to_cultivate(acres_owned, population, bushels_in_storage) #land to cultivate
    
    if is_plague(): #plague check
      plague_deaths += population // 2 #add deaths to plague count for print
      totalDeaths += population // 2 # add to stat variable
      population //= 2 #change population
    
    #get number starved
    numStarved = num_starving(population, bushels_for_food)
    totalDeaths += numStarved #totalDeaths done
    if numStarved / population >= 0.45:
      didStarveEnd = True #tell that game ended through overthrowing
      break
    
    #number of people coming
    immigrants = num_immigrants(acres_owned, bushels_in_storage, population, numStarved)

    #set bushels per acre cost and get harvest for print
    bushels_per_acre = get_harvest()
    harvest = bushels_per_acre * cultivatedLand
    totalBushelsMade += harvest #add to stat var
    
    #rat attack stuff
    if do_rats_infest():
      damage = percent_destroyed()
      rats_ate = int(damage * bushels_in_storage) #number of bushels the rats take
      bushels_in_storage -= rats_ate #change bushels in storage
      totalRatDam += damage #add to stat var

    cost_per_acre = price_of_land()
  
  print()
  #endgame
  if didStarveEnd:
    print("You let your people starve to death, you're bad :/")
    print(''' Here are some stats: ''')
    print("You starved:", totalStarved, "people to death.")
    print("A total of", totalDeaths,"people died while under your rule. I suppose sacrifices must be made.")
    print("You made a total of", totalBushelsMade, "bushels during your rule.")
    print("You lost a total of", totalRatDam, "bushels to rats")
  else:
    print("Congrats, you made it to the end without your people overthrowing you!")
    print(''' Here are some stats: ''')
    print("You starved:", totalStarved, "people to death.")
    print("A total of", totalDeaths,"people died while under your rule. I suppose sacrifices must be made.")
    print("You made a total of", totalBushelsMade, "bushels during your rule.")
    print("You lost a total of", totalRatDam, "bushels to rats")
    

# i actually commented on my code wow amazing  
Hammurabi()

