# -*- coding: utf-8 -*-
"""Project_Proposal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BusBDdYY077gzzlK_mkQXkGUZEz9TCqF

# Project Proposal for <font color='green'>Brian Hu, Yixiang Chen, Joshua Li</font>

Kaggle

https://www.kaggle.com/datasets

CORGIS datasets

https://corgis-edu.github.io/corgis/csv/

Open data projects (many cities participate in this)

https://www.opendataphilly.org/dataset

https://opendata.cityofnewyork.us/data/

Stack overflow user surveys (if you want to know what CS professionals are like..)

https://insights.stackoverflow.com/survey

Info from Tableau

https://www.tableau.com/learn/articles/free-public-data-sets

## Describe the data that you’ve selected for this project.
"""



"""## What information is contained in this data? Write a general description. Then, describe the specific variables in the dataset. If there are columns you do not understand, try and figure out what they mean. If you cannot get that information, you should probably remove those columns when you begin your actual analysis.

This data contains the stats of NBA players in the 2020-2021 season. The columns include player name, age, position, team, number of games, minutes played, player efficiency rating, shooting %, 3 point attempt rate, free throw attempt rate. All columns are clearly labeled on the website but badly labeled in the csv data chart, so we will rename the columns in the csv data chart.

##How big is your dataset? Specifically, how many distinct points of data do you have (usually this will just be the number of rows)

There are 481 unique values, meaning there are 481 players in the 2020-2021 NBA season.

## Where was this information collected from? Where did you get your data? Please provide a URL if possible. If your data is currently some kind of table on a website, please highlight this.

This information was collected from kaggle. The link for the data is attached below, although an account may be needed to access the data.
https://www.kaggle.com/datasets/a431e6fbff68669f62ed8fe885478db6169377f24bd818a25a3e8f52ada615c7?resource=download

## Why did you pick your data? What about that particular dataset do you find interesting? Also how much do you and your teammate(s) know about this domain

Ever since a young age, two out of the three of us have been engrossed in the game of basketball and share a similar immense passion for the sport. Ranging from worldwide, lengendary stars to the unnoticed players throughout the NBA, this dataset provides an accurate and complete representation of their career statistics. If we take Brian Hu out of the picture, we can confidently remark that we have a decently adequate amount of knowledge on the game of basketball.

### Is there any additional data that might help you? Any thoughts on where you might be able to get that data? 

Note: There is no harm in just sticking to the original dataset. Depending on your domain, getting additional data may/may not be feasible.

With the copious amount of data provided to us from this specific dataset, we believe extra data will prove unnecessary.

### Can you think of any issues with the data? (Some examples: small sample size, biased sampling etc)

It has quite a large number of columns, making navigation through this particular dataset difficult.
"""



