# -*- coding: utf-8 -*-
"""songgenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aN5lD4WiK7vi-TPLpi8YlRVqL5eLIkux
"""

def comparison(compare, phrase, addedPhrase, combinedPhrase):
  print("")
  
  sentenceStarter()  
  print(compare)
  print(phrase)
  
  if(addedPhrase != ""):
    print(addedPhrase)
  
  print(combinedPhrase)

  return addedPhrase

def sentenceStarter():
  print("I'm in love with a girl named Fred.")

def songgenerator():
  combinedPhrase = 'With a "F" and a "R" and an "E" and a "D"' + "\n" + 'And a "F-R-E-D" Fred!  Yeah!'

  print("I like you, Fred, I like you!")
  print("You're just saying those words to be kind.")
  print("No, I mean it.  I like... I mean I love you, Fred!")
  print("He is out of his medieval mind!")
  print("I'm perfectly sane and sound! I never felt better in my life!")
  print("Everybody... everybody, everybody! Come on! And meet my incipient wife!")

  combinedPhrase = comparison("My reasons must be clear.", "When she shows you all how strong she is you'll stand right up and cheer!", "", combinedPhrase) + combinedPhrase
  combinedPhrase = comparison("She drinks just like a lord!", "So sing a merry drinking song and let the wine be poured!", "Fill the bowl to overflowing.  Raise the goblet high!", combinedPhrase) + "\n" + combinedPhrase
  combinedPhrase = comparison("She sings just like a bird!", "You'll be left completely speechless when her gentle voice is heard!", "La la la la, la la la la, la la la la la!", combinedPhrase)  + "\n" +  combinedPhrase
  combinedPhrase = comparison("She wrestles like a Greek!", "You will clap your hands in wonder at her fabulous technique!", "Clap clap, clap clap, clap clap clap clap, clap, clap clap!", combinedPhrase)  + "\n" +  combinedPhrase
  combinedPhrase = comparison("She dances with such grace!", "You are bound to sing her praises 'til you're purple in the face!", "Bravo!  Bravo!  Bravissimo bravo!  Bravissimo!", combinedPhrase)  + "\n" +  combinedPhrase
  combinedPhrase = comparison("She's musical to boot!", "She will set your feet a-tapping when she plays upon her lute!", "Strum strum, strum strum, strum strum strum strum strum, strum.", combinedPhrase)  + "\n" +  combinedPhrase
  combinedPhrase = comparison("A clever, clownish wit!", "When she does her funny pantomime your sides are sure to split!", "Ha ha ha ha, ho ho ho ho, ha ha ha ha ho!", combinedPhrase)  + "\n" +  combinedPhrase
  
  
  print("\nI'm in love with a girl.")
  print("He's in love a girl named \"F-R-E-D\" Fred!")

songgenerator()