# -*- coding: utf-8 -*-
"""stringercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rw_m9eHidSecYQYtue_7RcHMCRYolSAm
"""

#1
def indent(n): 
  return " " * n

#2
def is_true(s): 
  return s.strip().lower() == "true"

#3
def contains_rep(s, t): 
  return t in s

#4
def shift_char(ch, n):
  ch.lower() 
  number = ord(ch)
  convert = number + n
  if(convert > 122):
    convert = 97 + (convert-122 - 1)
  elif convert < 97:
    convert = 122 - (97 - convert - 1)
  return chr(convert)

#5
def average_ch(s):
  tot = 0
  for i in s:
    tot += ord(i)
  return chr(tot // len(s))

#6
def mixed_case(s):
  ret = ""
  for i in range(1, len(s)+1):
    if i % 2 == 0:
      ret += s[i-1].upper()
    else:
      ret += s[i-1].lower()
  return ret

#7
def occurrences(s, t):
  count = 0
  for i in range (0, len(s)):
    if s[i : len(t)+i] == t:
      count += 1
  return count

#8 techinhcally since this isnt numbered properly on the site
def sum_numbers(s):
  ret = 0 
  addedNum = "0"
  for i in s:
    if i.isnumeric():
      addedNum += i
    else: 
      ret += int(addedNum)
      addedNum = "0"
  ret += int(addedNum)
  return ret

#9
def intersperse(s, t):
  ret = ""
  for i in range(0, len(s)):
    if(i != len(s)-1):
      ret += s[i]+t 
  ret += s[len(s)-1]
  return ret

#10
def swap_at(s, n):
  return s[n:] + s[:n]

#11
def evaluate(s):
  ret = 0
  counter = 0
  triggerMinus = False
  i = 0
  s = '0' + s

  for i2 in s:
    
    if i2 == '+':

      if triggerMinus:
        ret += int(s[i-counter: i])
        triggerMinus = False
        counter = 0
      else:
        ret += int(s[i - counter : i])
        counter = 0

    elif i2 == '-':

      if triggerMinus:
        ret += int(s[i-counter : i])
        triggerMinus = False
        counter = 0
      else:
        ret += int(s[i - counter : i])
        counter = 0
      
      triggerMinus = True
    i += 1
    counter += 1
  
  if triggerMinus:
    ret += int(s[i-counter : ])

    counter = 0
  else:
    ret += int(s[i - counter : ])
    counter = 0
  return ret
    


def main():
  print(indent(2) + "wasdwasdwasd")
  print("no" + indent(1) + "hi")
  print(is_true("                                   tRuE                 "))
  print(is_true("trua"))
  print(contains_rep("wasdwasdwasdwasdawsd", "wasd"))
  print(contains_rep("aaaaaaaa", "aa"))
  print(shift_char("z", 4))
  print(shift_char("a", -3))
  print(shift_char("a", 4))
  print(average_ch("abc"))
  print(average_ch("xyz"))
  print(mixed_case("hello world!"))
  print(mixed_case("goose questions.wasd"))
  print(occurrences('mississippi', 'ss'))
  print(occurrences('aaaaa', 'aa'))
  print(sum_numbers("7             123          10"))
  print(sum_numbers(" 1 2  3 4 5 6 7"))
  print(intersperse("hello world", '-'))
  print(intersperse("good bye", '-'))
  print(swap_at('hello world!', 5))
  print(evaluate("2+4-123"))
  print(evaluate("1+2+3-4"))
  print(evaluate("-1"))
  print(evaluate("-1-4"))
  print(evaluate("-1+1-1+1"))
  print(evaluate("224"))
main()

